POST https://odin-blog-api-ycwong66.adaptable.app/v1/user/sign-in/
content-type: application/json

{
    "username": "admin1",
    "password": "admin1"
}

###
 admin1 - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

 user1  - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzM3MjVmMGM4YTU3ZjhhZTE0NSIsInVzZXJuYW1lIjoidXNlcjEiLCJfX3YiOjB9LCJpYXQiOjE3MjAyMDAyNTMsImV4cCI6MTcyMDI4NjY1M30.kXqcceqUlAD3z4nkFAfooiyLRd0dh8ClyoBpbYzvv60
###
POST https://odin-blog-api-ycwong66.adaptable.app/v1/user/sign-up/
content-type: application/json

{
    "username": "user1",
    "password": "user1",
    "confirmPassword": "user1",
    "adminCode": "123456789"
}

###
GET https://odin-blog-api-ycwong66.adaptable.app/v1/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

###
POST https://odin-blog-api-ycwong66.adaptable.app/v1/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

{
    "title": "test-title-4",
    "contents": "test-title-4",
    "isPublished": "true"
}

###
GET https://odin-blog-api-ycwong66.adaptable.app/v1/posts/66882cc425f0c8a57f8ae14e
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

###

PUT https://odin-blog-api-ycwong66.adaptable.app/v1/posts/66882cc425f0c8a57f8ae14e
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

{
    "title": "updated-title-2",
    "contents": "updated-contents-2",
    "isPublished": "true"
}

###
DELETE https://odin-blog-api-ycwong66.adaptable.app/v1/posts/66882e6225f0c8a57f8ae165
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

###
#-------------- COMMMENTS --------------
###

###
GET https://odin-blog-api-ycwong66.adaptable.app/v1/comments/66882cc425f0c8a57f8ae14e/
content-type: application/json

###
POST https://odin-blog-api-ycwong66.adaptable.app/v1/comments/66882cc425f0c8a57f8ae14e/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

{
    "text" : "new comment -by admin4"
}

###
PUT https://odin-blog-api-ycwong66.adaptable.app/v1/comments/66882ec825f0c8a57f8ae17b/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

{
    "text" : "updated comment - by admin 3"
}

###
DELETE https://odin-blog-api-ycwong66.adaptable.app/v1/comments/66882f0d25f0c8a57f8ae18c/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY2ODgyYzBhMjVmMGM4YTU3ZjhhZTE0MiIsInVzZXJuYW1lIjoiYWRtaW4xIiwiX192IjowfSwiaWF0IjoxNzIwMjAwMjgwLCJleHAiOjE3MjAyODY2ODB9.4tLLG1o1VsQ1IcbOpGXaS3MReHMpqhjceIOd1N1oCTY

###