POST http://localhost:3000/v1/user/sign-in/
content-type: application/json

{
    "username": "user1",
    "password": "user1"
}
###
admin1 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

user1 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjozLCJ1c2VybmFtZSI6InVzZXIxIn0sImlhdCI6MTcyNDM1MTIwOSwiZXhwIjoxNzI0NDM3NjA5fQ.VcXOR34VIQrICS6cBtJ4UR4bY3_vekVUKxeLOlvehnk

###

###
POST http://localhost:3000/v1/user/sign-up/
content-type: application/json

{
    "username": "user1",
    "password": "user1",
    "confirmPassword": "user1",
    "adminCode": "1234567811"
}

###
GET http://localhost:3000/v1/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

###
POST http://localhost:3000/v1/posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

{
    "title": "test-title-5",
    "contents": "test-title-5",
    "isPublished": "true"
}

###
GET http://localhost:3000/v1/posts/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

###

PUT http://localhost:3000/v1/posts/5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

{
    "title": "updated-title-5",
    "contents": "updated-contents-5",
    "isPublished": "true"
}

###
DELETE http://localhost:3000/v1/posts/4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

###
#-------------- COMMMENTS --------------
###

###
GET http://localhost:3000/v1/comments/1/
content-type: application/json

###
POST http://localhost:3000/v1/comments/1/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

{
    "text" : "new comment by admin1"
}

###
PUT http://localhost:3000/v1/comments/3/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

{
    "text" : "updated comment 3 - by admin1"
}

###
DELETE http://localhost:3000/v1/comments/4/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6ImFkbWluMSJ9LCJpYXQiOjE3MjQzNDE0NDMsImV4cCI6MTcyNDQyNzg0M30.jn4KvryxD67W_R00k3SCO08oN9fh7jkIgQqZJkyEWDc

###